---
- name: Prepare
  hosts: all
  tasks:
    - name: Refresh yum cache <= EL7
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version <= "7"
    - name: Install required packages for EL 7
      package:
        name:
          - openssl11-libs
          - libzstd-devel
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
