---
name: CI
'on':
  pull_request:
  push:
    branches:
      - netways


jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint .

  molecule-default:
    name: Molecule (default)
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      max-parallel: 1
      matrix:
        distro:
          #- debian9    # TODO
          #- debian10   # TODO
          - rockylinux8
          - rockylinux9
        scenario:
          # - patroni-default   #TODO
          - patroni-etcdv2-ssl
          #- patroni-etcdv3-nossl   # TODO
          - patroni-etcdv3-ssl

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install ansible molecule[docker] docker

      - name: Install test dependencies.
        run: sudo apt update

      - name: Install test dependencies.
        run: sudo apt install libssl-dev

      - name: Run Molecule tests
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
